// frontend/src/Frontpage.tsx
import './Frontpage.css'

function Frontpage() {
    return (
        <div>
            <h1>Welcome to the Frontpage</h1>
            <p>This is a simple frontpage component.</p>
            <div className="mtg">
                <button onClick={() => window.location.href = '/mtgInput'}>
                    MTG Data Tracker </button>
                <button onClick={() => window.location.href = '/mtgAnalysis'}>
                    MTG Data Analysis </button>
            </div>
        </div>
    )
}

export default Frontpage;

// frontend-angular/src/app/frontpage/frontpage.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-frontpage',
  standalone: true,
  imports: [],
  templateUrl: './frontpage.component.html',
  styleUrl: './frontpage.component.css'
})
export class FrontpageComponent {

    navigateTo(url: string): void {
        window.location.href = url;
    }

}

<div>
    <h1>Welcome to the Frontpage</h1>
    <p>This is a simple frontpage component.</p>
    <div className="mtg">
        <button class="mtg" (click)="navigateTo('/mtgInput')">
            MTG Data Tracker
        </button>
        <button class="mtg" (click)="navigateTo('/mtgAnalysis')">
            MTG Data Analysis
        </button>
    </div>
</div>
